package com.hitices.common.bean.groupagent;

/**
 * @author septemberhx
 * @date 2020/7/24
 *
 * Hold the evolution plan generated by the group agent during evolution
 *
 **/

public enum MGroupContextLevel {
    // Only current group context
    LEVEL_0,

    // Instance info and overload
    LEVEL_1,

    // User info, instance info and overload
    LEVEL_2,

    // User history, user info, instance info and overload
    // ATTENTION: The meaning of the value may change in the future.
    //   However, LEVEL_3 always stands for the maximum context
    LEVEL_3
}
