package com.hitices.common.base.job;

import com.hitices.common.base.MEndPoint;
import com.hitices.common.bean.agent.MDeployPodRequest;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class MDeployJob extends MBaseJob {
    private String nodeId;
    private String imageName;
    private String serviceName;

    /*
     * unique instance id (podId) that generated by the planner
     */
    private String uniqueId;

    public MDeployJob(String nodeId, String serviceName, String uniqueId, String imageName) {
        this(nodeId, serviceName, uniqueId, imageName, "");
    }

    public MDeployJob(String nodeId, String serviceName, String uniqueId, String imageName, String groupName) {
        super(MJobType.JOB_DEPLOY, groupName);
        this.nodeId = nodeId;
        this.serviceName = serviceName;
        this.uniqueId = uniqueId;
        this.imageName = imageName;
    }

    public MDeployPodRequest toMDeployPodRequest(MEndPoint groupEntry) {
        return new MDeployPodRequest(id, nodeId, uniqueId, serviceName, imageName, groupEntry);
    }
}
